package cpu6502

type instruction struct {
	name           string
	operate        func() uint8
	addrMode       func() uint8
	cyclesRequired uint8
}

// Initialise a big 16x16 instruction lookup table, as defined by the datasheet
// It's not pretty but it's clear
// Ref: https://github.com/OneLoneCoder/olcNES/blob/master/Part%232%20-%20CPU/olc6502.cpp
func (c *Cpu) initInstLookup() {
	c.insLookup = []instruction{
		{"BRK", c.BRK, c.IMM, 7}, {"ORA", c.ORA, c.IZX, 6}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 3}, {"ORA", c.ORA, c.ZP0, 3}, {"ASL", c.ASL, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"PHP", c.PHP, c.IMP, 3}, {"ORA", c.ORA, c.IMM, 2}, {"ASL", c.ASL, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"???", c.NOP, c.IND, 4}, {"ORA", c.ORA, c.ABS, 4}, {"ASL", c.ASL, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BPL", c.BPL, c.REL, 2}, {"ORA", c.ORA, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"ORA", c.ORA, c.ZPX, 4}, {"ASL", c.ASL, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"CLC", c.CLC, c.IMP, 2}, {"ORA", c.ORA, c.ABY, 4}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"ORA", c.ORA, c.ABX, 4}, {"ASL", c.ASL, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
		{"JSR", c.JSR, c.ABS, 6}, {"AND", c.AND, c.IZX, 6}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"BIT", c.BIT, c.ZP0, 3}, {"AND", c.AND, c.ZP0, 3}, {"ROL", c.ROL, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"PLP", c.PLP, c.IMP, 4}, {"AND", c.AND, c.IMM, 2}, {"ROL", c.ROL, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"BIT", c.BIT, c.ABS, 4}, {"AND", c.AND, c.ABS, 4}, {"ROL", c.ROL, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BMI", c.BMI, c.REL, 2}, {"AND", c.AND, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"AND", c.AND, c.ZPX, 4}, {"ROL", c.ROL, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"SEC", c.SEC, c.IMP, 2}, {"AND", c.AND, c.ABY, 4}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"AND", c.AND, c.ABX, 4}, {"ROL", c.ROL, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
		{"RTI", c.RTI, c.IMP, 6}, {"EOR", c.EOR, c.IZX, 6}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 3}, {"EOR", c.EOR, c.ZP0, 3}, {"LSR", c.LSR, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"PHA", c.PHA, c.IMP, 3}, {"EOR", c.EOR, c.IMM, 2}, {"LSR", c.LSR, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"JMP", c.JMP, c.ABS, 3}, {"EOR", c.EOR, c.ABS, 4}, {"LSR", c.LSR, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BVC", c.BVC, c.REL, 2}, {"EOR", c.EOR, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"EOR", c.EOR, c.ZPX, 4}, {"LSR", c.LSR, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"CLI", c.CLI, c.IMP, 2}, {"EOR", c.EOR, c.ABY, 4}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"EOR", c.EOR, c.ABX, 4}, {"LSR", c.LSR, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
		{"RTS", c.RTS, c.IMP, 6}, {"ADC", c.ADC, c.IZX, 6}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 3}, {"ADC", c.ADC, c.ZP0, 3}, {"ROR", c.ROR, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"PLA", c.PLA, c.IMP, 4}, {"ADC", c.ADC, c.IMM, 2}, {"ROR", c.ROR, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"JMP", c.JMP, c.IND, 5}, {"ADC", c.ADC, c.ABS, 4}, {"ROR", c.ROR, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BVS", c.BVS, c.REL, 2}, {"ADC", c.ADC, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"ADC", c.ADC, c.ZPX, 4}, {"ROR", c.ROR, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"SEI", c.SEI, c.IMP, 2}, {"ADC", c.ADC, c.ABY, 4}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"ADC", c.ADC, c.ABX, 4}, {"ROR", c.ROR, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
		{"???", c.NOP, c.IMM, 2}, {"STA", c.STA, c.IZX, 6}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 6}, {"STY", c.STY, c.ZP0, 3}, {"STA", c.STA, c.ZP0, 3}, {"STX", c.STX, c.ZP0, 3}, {"???", c.XXX, c.IMP, 3}, {"DEY", c.DEY, c.IMP, 2}, {"???", c.NOP, c.IMP, 2}, {"TXA", c.TXA, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"STY", c.STY, c.ABS, 4}, {"STA", c.STA, c.ABS, 4}, {"STX", c.STX, c.ABS, 4}, {"???", c.XXX, c.IMP, 4},
		{"BCC", c.BCC, c.REL, 2}, {"STA", c.STA, c.IZY, 6}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 6}, {"STY", c.STY, c.ZPX, 4}, {"STA", c.STA, c.ZPX, 4}, {"STX", c.STX, c.ZPY, 4}, {"???", c.XXX, c.IMP, 4}, {"TYA", c.TYA, c.IMP, 2}, {"STA", c.STA, c.ABY, 5}, {"TXS", c.TXS, c.IMP, 2}, {"???", c.XXX, c.IMP, 5}, {"???", c.NOP, c.IMP, 5}, {"STA", c.STA, c.ABX, 5}, {"???", c.XXX, c.IMP, 5}, {"???", c.XXX, c.IMP, 5},
		{"LDY", c.LDY, c.IMM, 2}, {"LDA", c.LDA, c.IZX, 6}, {"LDX", c.LDX, c.IMM, 2}, {"LAX", c.LAX, c.IZX, 6}, {"LDY", c.LDY, c.ZP0, 3}, {"LDA", c.LDA, c.ZP0, 3}, {"LDX", c.LDX, c.ZP0, 3}, {"LAX", c.LAX, c.ZP0, 3}, {"TAY", c.TAY, c.IMP, 2}, {"LDA", c.LDA, c.IMM, 2}, {"TAX", c.TAX, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"LDY", c.LDY, c.ABS, 4}, {"LDA", c.LDA, c.ABS, 4}, {"LDX", c.LDX, c.ABS, 4}, {"LAX", c.LAX, c.ABS, 4},
		{"BCS", c.BCS, c.REL, 2}, {"LDA", c.LDA, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"LAX", c.LAX, c.IZY, 5}, {"LDY", c.LDY, c.ZPX, 4}, {"LDA", c.LDA, c.ZPX, 4}, {"LDX", c.LDX, c.ZPY, 4}, {"LAX", c.LAX, c.ZPY, 4}, {"CLV", c.CLV, c.IMP, 2}, {"LDA", c.LDA, c.ABY, 4}, {"TSX", c.TSX, c.IMP, 2}, {"???", c.XXX, c.IMP, 4}, {"LDY", c.LDY, c.ABX, 4}, {"LDA", c.LDA, c.ABX, 4}, {"LDX", c.LDX, c.ABY, 4}, {"LAX", c.LAX, c.ABY, 4},
		{"CPY", c.CPY, c.IMM, 2}, {"CMP", c.CMP, c.IZX, 6}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"CPY", c.CPY, c.ZP0, 3}, {"CMP", c.CMP, c.ZP0, 3}, {"DEC", c.DEC, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"INY", c.INY, c.IMP, 2}, {"CMP", c.CMP, c.IMM, 2}, {"DEX", c.DEX, c.IMP, 2}, {"???", c.XXX, c.IMP, 2}, {"CPY", c.CPY, c.ABS, 4}, {"CMP", c.CMP, c.ABS, 4}, {"DEC", c.DEC, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BNE", c.BNE, c.REL, 2}, {"CMP", c.CMP, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"CMP", c.CMP, c.ZPX, 4}, {"DEC", c.DEC, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"CLD", c.CLD, c.IMP, 2}, {"CMP", c.CMP, c.ABY, 4}, {"NOP", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"CMP", c.CMP, c.ABX, 4}, {"DEC", c.DEC, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
		{"CPX", c.CPX, c.IMM, 2}, {"SBC", c.SBC, c.IZX, 6}, {"???", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"CPX", c.CPX, c.ZP0, 3}, {"SBC", c.SBC, c.ZP0, 3}, {"INC", c.INC, c.ZP0, 5}, {"???", c.XXX, c.IMP, 5}, {"INX", c.INX, c.IMP, 2}, {"SBC", c.SBC, c.IMM, 2}, {"NOP", c.NOP, c.IMP, 2}, {"???", c.SBC, c.IMP, 2}, {"CPX", c.CPX, c.ABS, 4}, {"SBC", c.SBC, c.ABS, 4}, {"INC", c.INC, c.ABS, 6}, {"???", c.XXX, c.IMP, 6},
		{"BEQ", c.BEQ, c.REL, 2}, {"SBC", c.SBC, c.IZY, 5}, {"???", c.XXX, c.IMP, 2}, {"???", c.XXX, c.IMP, 8}, {"???", c.NOP, c.IMM, 4}, {"SBC", c.SBC, c.ZPX, 4}, {"INC", c.INC, c.ZPX, 6}, {"???", c.XXX, c.IMP, 6}, {"SED", c.SED, c.IMP, 2}, {"SBC", c.SBC, c.ABY, 4}, {"NOP", c.NOP, c.IMP, 2}, {"???", c.XXX, c.IMP, 7}, {"???", c.NOP, c.IND, 4}, {"SBC", c.SBC, c.ABX, 4}, {"INC", c.INC, c.ABX, 7}, {"???", c.XXX, c.IMP, 7},
	}
}
